FROM ubuntu:16.04
RUN apt-get update && apt-get install -y git build-essential \
checkinstall \
libreadline-gplv2-dev \
libncursesw5-dev \
libssl-dev \
libsqlite3-dev \
tk-dev \
libgdbm-dev \
libc6-dev \
libbz2-dev \
zlib1g-dev \
openssl \
libffi-dev \
python3-dev \
python3-setuptools \
wget
COPY install_python.sh /install_python.sh
RUN chmod +x /install_python.sh
RUN /install_python.sh
