version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    networks:
      - fastoauth 
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword 
    volumes:
      - ./endurance/postgres:/var/lib/postgresql/data

networks:
  fastoauth:
