version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    networks:
      - metastacks
    environment:
      POSTGRES_PASSWORD: mysecretpassword 

  adminer:
    image: adminer
    restart: always
    networks:
      - metastacks
    ports:
      - 8081:8080

networks:
  metastacks:
